<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>wonderautomation</AssemblyName>
    <RootNamespace>Calloatti.WonderAutomation</RootNamespace>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />
  
  <PropertyGroup>
    <TimberbornPath>C:\Program Files (x86)\Steam\steamapps\common\timberborn_experimental\Timberborn_Data\Managed</TimberbornPath>
  </PropertyGroup>

</Project>